spring.application.name=QuillHub

# DATABASE (local + Render)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/quill}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Root@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:prashanth9392557522@gmail.com}
spring.mail.password=${MAIL_PASSWORD:YOUR_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PORT
server.port=${PORT:8080}